# tile 0 (giant ant)
{
  model = x_rot.md2
  skin  = x_rot.png
}
# tile 1 (killer bee)
{
  model = x_rot.md2
  skin  = x_rot.png
}
# tile 2 (soldier ant)
{
  model = x_rot.md2
  skin  = x_rot.png
}
# tile 3 (fire ant)
{
  model = x_rot.md2
  skin  = x_rot.png
}
# tile 4 (giant beetle)
{
  model = x_rot.md2
  skin  = x_rot.png
}
# tile 5 (queen bee)
{
  model = x_rot.md2
  skin  = x_rot.png
}
# tile 6 (acid blob)
{
  model = x_blob.md2
  skin  = x_blob.png
}
# tile 7 (quivering blob)
{
  model = x_blob.md2
  skin  = x_blob.png
}
# tile 8 (gelatinous cube)
{
  model = x_blob.md2
  skin  = x_blob.png
}
# tile 9 (chickatrice)
{
}
# tile 10 (cockatrice)
{
}
# tile 11 (pyrolisk)
{
}
# tile 12 (jackal)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 13 (fox)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 14 (coyote)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 15 (werejackal)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 16 (little dog)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 17 (dog)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 18 (large dog)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 19 (dingo)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 20 (wolf)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 21 (werewolf)
{
  model = x_bullwolf.md2
  skin  = x_bullwolf.png
}
# tile 22 (warg)
{
  model = x_hotdog.md2
  skin  = x_hotdog.png
}
# tile 23 (winter wolf cub)
{
  model = x_hotdog.md2
  skin  = x_hotdog.png
}
# tile 24 (winter wolf)
{
  model = x_hotdog.md2
  skin  = x_hotdog.png
}
# tile 25 (hell hound pup)
{
  model = x_hotdog.md2
  skin  = x_hotdog.png
}
# tile 26 (hell hound)
{
  model = x_hotdog.md2
  skin  = x_hotdog.png
}
# tile 27 (Cerberus)
{
  model = x_hotdog.md2
  skin  = x_hotdog.png
}
# tile 28 (gas spore)
{
}
# tile 29 (floating eye)
{
}
# tile 30 (freezing sphere)
{
}
# tile 31 (flaming sphere)
{
  light = FlamingSphere
}
# tile 32 (shocking sphere)
{
  light = ShockingSphere
}
# tile 33 (beholder)
{
}
# tile 34 (kitten)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 35 (housecat)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 36 (jaguar)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 37 (lynx)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 38 (panther)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 39 (large cat)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 40 (tiger)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 41 (gremlin)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 42 (gargoyle)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 43 (winged gargoyle)
{
  model = x_bosslump.md2
  skin  = x_bosslump.png
}
# tile 44 (hobbit)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 45 (dwarf)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 46 (bugbear)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 47 (dwarf lord)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 48 (dwarf king)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 49 (mind flayer)
{
}
# tile 50 (master mind flayer)
{
}
# tile 51 (manes)
{
}
# tile 52 (homunculus)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 53 (imp)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 54 (lemure)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 55 (quasit)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 56 (tengu)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 57 (blue jelly)
{
  model = x_blob.md2
  skin  = x_blob.png
}
# tile 58 (spotted jelly)
{
  model = x_blob.md2
  skin  = x_blob.png
}
# tile 59 (ochre jelly)
{
  model = x_blob.md2
  skin  = x_blob.png
}
# tile 60 (kobold)
{
  model = x_cobol.md2
  skin  = x_cobol.png
}
# tile 61 (large kobold)
{
  model = x_cobol.md2
  skin  = x_cobol.png
}
# tile 62 (kobold lord)
{
  model = x_cobol.md2
  skin  = x_cobol.png
}
# tile 63 (kobold shaman)
{
  model = x_cobol.md2
  skin  = x_cobol.png
}
# tile 64 (leprechaun)
{
}
# tile 65 (small mimic)
{
}
# tile 66 (large mimic)
{
}
# tile 67 (giant mimic)
{
}
# tile 68 (wood nymph)
{
}
# tile 69 (water nymph)
{
}
# tile 70 (mountain nymph)
{
}
# tile 71 (goblin)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 72 (hobgoblin)
{
  model = x_rogue.md2
  skin  = x_rogue.png
}
# tile 73 (orc)
{
}
# tile 74 (hill orc)
{
}
# tile 75 (Mordor orc)
{
}
# tile 76 (Uruk-hai)
{
}
# tile 77 (orc shaman)
{
}
# tile 78 (orc-captain)
{
}
# tile 79 (rock piercer)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 80 (iron piercer)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 81 (glass piercer)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 82 (rothe)
{
  model = x_lamb.md2
  skin  = x_lamb.png
}
# tile 83 (mumak)
{
}
# tile 84 (leocrotta)
{
}
# tile 85 (wumpus)
{
}
# tile 86 (titanothere)
{
}
# tile 87 (baluchitherium)
{
}
# tile 88 (mastodon)
{
}
# tile 89 (sewer rat)
{
  model = x_mouse.md2
  skin  = x_mouse.png
}
# tile 90 (giant rat)
{
  model = x_mouse.md2
  skin  = x_mouse.png
}
# tile 91 (rabid rat)
{
  model = x_mouse.md2
  skin  = x_mouse.png
}
# tile 92 (wererat)
{
  model = x_mouse.md2
  skin  = x_mouse.png
}
# tile 93 (rock mole)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 94 (woodchuck)
{
  model = x_mouse.md2
  skin  = x_mouse.png
}
# tile 95 (cave spider)
{
  model = x_tranch.md2
  skin  = x_tranch.png
}
# tile 96 (centipede)
{
  model = x_tranch.md2
  skin  = x_tranch.png
}
# tile 97 (giant spider)
{
  model = x_tranch.md2
  skin  = x_tranch.png
}
# tile 98 (scorpion)
{
  model = x_bossscor.md2
  skin  = x_bossscor.png
}
# tile 99 (lurker above)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 100 (trapper)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 101 (white unicorn)
{
}
# tile 102 (gray unicorn)
{
}
# tile 103 (black unicorn)
{
}
# tile 104 (pony)
{
}
# tile 105 (horse)
{
}
# tile 106 (warhorse)
{
}
# tile 107 (fog cloud)
{
}
# tile 108 (dust vortex)
{
}
# tile 109 (ice vortex)
{
}
# tile 110 (energy vortex)
{
}
# tile 111 (steam vortex)
{
}
# tile 112 (fire vortex)
{
  light = FireVortex
}
# tile 113 (baby long worm)
{
  model = x_bossgrub.md2
  skin  = x_bossgrub.png
}
# tile 114 (baby purple worm)
{
  model = x_bossgrub.md2
  skin  = x_bossgrub.png
}
# tile 115 (long worm)
{
  model = x_bossgrub.md2
  skin  = x_bossgrub.png
}
# tile 116 (purple worm)
{
  model = x_bossgrub.md2
  skin  = x_bossgrub.png
}
# tile 117 (grid bug)
{
  model = x_bossgrub.md2
  skin  = x_bossgrub.png
}
# tile 118 (xan)
{
  model = x_bossgrub.md2
  skin  = x_bossgrub.png
}
# tile 119 (yellow light)
{
  light = YellowLight
}
# tile 120 (black light)
{
  light = BlackLight
}
# tile 121 (zruty)
{
}
# tile 122 (couatl)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 123 (Aleax)
{
}
# tile 124 (Angel)
{
  model = x_ffaerie.md2
  skin  = x_ffaerie.png
}
# tile 125 (ki-rin)
{
}
# tile 126 (Archon)
{
}
# tile 127 (bat)
{
  model = x_crab.md2
  skin  = x_crab.png
}
# tile 128 (giant bat)
{
  model = x_crab.md2
  skin  = x_crab.png
}
# tile 129 (raven)
{
  model = x_crab.md2
  skin  = x_crab.png
}
# tile 130 (vampire bat)
{
  model = x_crab.md2
  skin  = x_crab.png
}
# tile 131 (plains centaur)
{
}
# tile 132 (forest centaur)
{
}
# tile 133 (mountain centaur)
{
}
# tile 134 (baby gray dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 135 (baby silver dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 136 (baby shimmering dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 137 (baby red dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 138 (baby white dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 139 (baby orange dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 140 (baby black dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 141 (baby blue dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 142 (baby green dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 143 (baby yellow dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 144 (gray dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 145 (silver dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 146 (shimmering dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 147 (red dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 148 (white dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 149 (orange dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 150 (black dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 151 (blue dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 152 (green dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 153 (yellow dragon)
{
  model = x_trog.md2
  skin  = x_trog.png
}
# tile 154 (stalker)
{
  model = x_ulna.md2
  skin  = x_ulna.png
}
# tile 155 (air elemental)
{
}
# tile 156 (fire elemental)
{
  light = FireElemental
}
# tile 157 (earth elemental)
{
}
# tile 158 (water elemental)
{
}
# tile 159 (lichen)
{
}
# tile 160 (brown mold)
{
}
# tile 161 (yellow mold)
{
}
# tile 162 (green mold)
{
}
# tile 163 (red mold)
{
}
# tile 164 (shrieker)
{
}
# tile 165 (violet fungus)
{
}
# tile 166 (gnome)
{
  model = x_gnome.md2
  skin  = x_gnome.png
}
# tile 167 (gnome lord)
{
  model = x_gnome.md2
  skin  = x_gnome.png
}
# tile 168 (gnomish wizard)
{
  model = x_gnome.md2
  skin  = x_gnome.png
}
# tile 169 (gnome king)
{
  model = x_gnome.md2
  skin  = x_gnome.png
}
# tile 170 (giant)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 171 (stone giant)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 172 (hill giant)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 173 (fire giant)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 174 (frost giant)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 175 (storm giant)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 176 (ettin)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 177 (titan)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 178 (minotaur)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 179 (jabberwock)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 180 (vorpal jabberwock)
{
  model = x_bossdark.md2
  skin  = x_bossdark.png
}
# tile 181 (Keystone Kop)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 182 (Kop Sergeant)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 183 (Kop Lieutenant)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 184 (Kop Kaptain)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 185 (lich)
{
  model = x_ulna.md2
  skin  = x_ulna.png
}
# tile 186 (demilich)
{
  model = x_ulna.md2
  skin  = x_ulna.png
}
# tile 187 (master lich)
{
  model = x_ulna.md2
  skin  = x_ulna.png
}
# tile 188 (arch-lich)
{
  model = x_ulna.md2
  skin  = x_ulna.png
}
# tile 189 (kobold mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 190 (gnome mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 191 (orc mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 192 (dwarf mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 193 (elf mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 194 (human mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 195 (ettin mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 196 (giant mummy)
{
  model = x_ghoul.md2
  skin  = x_ghoul.png
}
# tile 197 (red naga hatchling)
{
}
# tile 198 (black naga hatchling)
{
}
# tile 199 (golden naga hatchling)
{
}
# tile 200 (guardian naga hatchling)
{
}
# tile 201 (red naga)
{
}
# tile 202 (black naga)
{
}
# tile 203 (golden naga)
{
}
# tile 204 (guardian naga)
{
}
# tile 205 (ogre)
{
}
# tile 206 (ogre lord)
{
}
# tile 207 (ogre king)
{
}
# tile 208 (gray ooze)
{
}
# tile 209 (brown pudding)
{
}
# tile 210 (black pudding)
{
}
# tile 211 (green slime)
{
}
# tile 212 (quantum mechanic)
{
}
# tile 213 (rust monster)
{
}
# tile 214 (disenchanter)
{
}
# tile 215 (garter snake)
{
}
# tile 216 (snake)
{
}
# tile 217 (water moccasin)
{
}
# tile 218 (pit viper)
{
}
# tile 219 (python)
{
}
# tile 220 (cobra)
{
}
# tile 221 (troll)
{
  model = x_bosstrol.md2
  skin  = x_bosstrol.png
}
# tile 222 (ice troll)
{
  model = x_bosstrol.md2
  skin  = x_bosstrol.png
}
# tile 223 (rock troll)
{
  model = x_bosstrol.md2
  skin  = x_bosstrol.png
}
# tile 224 (water troll)
{
  model = x_bosstrol.md2
  skin  = x_bosstrol.png
}
# tile 225 (Olog-hai)
{
  model = x_bosstrol.md2
  skin  = x_bosstrol.png
}
# tile 226 (umber hulk)
{
  model = x_bosstrol.md2
  skin  = x_bosstrol.png
}
# tile 227 (vampire)
{
}
# tile 228 (vampire lord)
{
}
# tile 229 (vampire mage)
{
}
# tile 230 (Vlad the Impaler)
{
}
# tile 231 (barrow wight)
{
}
# tile 232 (wraith)
{
}
# tile 233 (Nazgul)
{
}
# tile 234 (xorn)
{
}
# tile 235 (monkey)
{
}
# tile 236 (ape)
{
}
# tile 237 (owlbear)
{
}
# tile 238 (yeti)
{
}
# tile 239 (carnivorous ape)
{
}
# tile 240 (sasquatch)
{
}
# tile 241 (kobold zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 242 (gnome zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 243 (orc zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 244 (dwarf zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 245 (elf zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 246 (human zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 247 (ettin zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 248 (giant zombie)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 249 (ghoul)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 250 (skeleton)
{
  model = x_animate.md2
  skin  = x_animate.png
}
# tile 251 (straw golem)
{
}
# tile 252 (paper golem)
{
}
# tile 253 (rope golem)
{
}
# tile 254 (gold golem)
{
}
# tile 255 (leather golem)
{
}
# tile 256 (wood golem)
{
}
# tile 257 (flesh golem)
{
}
# tile 258 (clay golem)
{
}
# tile 259 (stone golem)
{
}
# tile 260 (glass golem)
{
}
# tile 261 (iron golem)
{
}
# tile 262 (human)
{
}
# tile 263 (wererat humanoid)
{
}
# tile 264 (werejackal humanoid)
{
}
# tile 265 (werewolf humanoid)
{
}
# tile 266 (elf)
{
}
# tile 267 (Woodland-elf)
{
}
# tile 268 (Green-elf)
{
}
# tile 269 (Grey-elf)
{
}
# tile 270 (elf-lord)
{
}
# tile 271 (Elvenking)
{
}
# tile 272 (doppelganger)
{
}
# tile 273 (nurse)
{
}
# tile 274 (shopkeeper)
{
  model = x_shopkeep.md2
  skin  = x_shopkeep.png
}
# tile 275 (guard)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 276 (prisoner)
{
  model = x_prisoner.md2
  skin  = x_prisoner.png
}
# tile 277 (Oracle)
{
  model = x_shopkeep.md2
  skin  = x_shopkeep.png
}
# tile 278 (aligned priest)
{
  model = x_shopkeep.md2
  skin  = x_shopkeep.png
}
# tile 279 (high priest)
{
  model = x_shopkeep.md2
  skin  = x_shopkeep.png
}
# tile 280 (soldier)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 281 (sergeant)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 282 (lieutenant)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 283 (captain)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 284 (watchman)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 285 (watch captain)
{
  model = x_guard.md2
  skin  = x_guard.png
}
# tile 286 (Medusa)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 287 (Wizard of Yendor)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 288 (Croesus)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 289 (Charon)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 290 (ghost)
{
  model = x_fright.md2
  skin  = x_fright.png
}
# tile 291 (shade)
{
  model = x_fright.md2
  skin  = x_fright.png
}
# tile 292 (water demon)
{
}
# tile 293 (horned devil)
{
}
# tile 294 (succubus)
{
}
# tile 295 (incubus)
{
}
# tile 296 (erinys)
{
}
# tile 297 (barbed devil)
{
}
# tile 298 (marilith)
{
}
# tile 299 (vrock)
{
}
# tile 300 (hezrou)
{
}
# tile 301 (bone devil)
{
}
# tile 302 (ice devil)
{
}
# tile 303 (nalfeshnee)
{
}
# tile 304 (pit fiend)
{
}
# tile 305 (balrog)
{
}
# tile 306 (Juiblex)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 307 (Yeenoghu)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 308 (Orcus)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 309 (Geryon)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 310 (Dispater)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 311 (Baalzebub)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 312 (Asmodeus)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 313 (Demogorgon)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 314 (Death)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 315 (Pestilence)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 316 (Famine)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 317 (mail daemon)
{
}
# tile 318 (djinni)
{
}
# tile 319 (sandestin)
{
}
# tile 320 (jellyfish)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 321 (piranha)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 322 (shark)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 323 (giant eel)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 324 (electric eel)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 325 (kraken)
{
  model = x_squidgie.md2
  skin  = x_squidgie.png
}
# tile 326 (newt)
{
  model = x_lamb.md2
  skin  = x_lamb.png
}
# tile 327 (gecko)
{
  model = x_lamb.md2
  skin  = x_lamb.png
}
# tile 328 (iguana)
{
}
# tile 329 (baby crocodile)
{
}
# tile 330 (lizard)
{
}
# tile 331 (chameleon)
{
}
# tile 332 (crocodile)
{
}
# tile 333 (salamander)
{
}
# tile 334 (long worm tail)
{
}
# tile 335 (archeologist)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 336 (barbarian)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 337 (caveman)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 338 (cavewoman)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 339 (healer)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 340 (knight)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 341 (monk)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 342 (priest)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 343 (priestess)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 344 (ranger)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 345 (rogue)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 346 (samurai)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 347 (tourist)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 348 (valkyrie)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 349 (wizard)
{
  model = x_advent.md2
  skin  = x_advent.png
}
# tile 350 (Lord Carnarvon)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 351 (Pelias)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 352 (Shaman Karnov)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 353 (Earendil)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 354 (Elwing)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 355 (Hippocrates)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 356 (King Arthur)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 357 (Grand Master)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 358 (Arch Priest)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 359 (Orion)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 360 (Master of Thieves)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 361 (Lord Sato)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 362 (Twoflower)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 363 (Norn)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 364 (Neferet the Green)
{
  model = x_knight.md2
  skin  = x_knight.png
}
# tile 365 (Minion of Huhetotl)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 366 (Thoth Amon)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 367 (Chromatic Dragon)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 368 (Goblin King)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 369 (Cyclops)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 370 (Ixoth)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 371 (Master Kaen)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 372 (Nalzok)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 373 (Scorpius)
{
  model = x_bossscor.md2
  skin  = x_bossscor.png
}
# tile 374 (Master Assassin)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 375 (Ashikaga Takauji)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 376 (Lord Surtur)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 377 (Dark One)
{
  model = x_bossnecr.md2
  skin  = x_bossnecr.png
}
# tile 378 (student)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 379 (chieftain)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 380 (neanderthal)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 381 (High-elf)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 382 (attendant)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 383 (page)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 384 (abbot)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 385 (acolyte)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 386 (hunter)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 387 (thug)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 388 (ninja)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 389 (roshi)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 390 (guide)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 391 (warrior)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 392 (apprentice)
{
  model = x_shep.md2
  skin  = x_shep.png
}
# tile 393 (invisible monster)
{
}
