# tile 394 (strange object)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 395 (arrow)
{
}
# tile 396 (runed arrow / elven arrow)
{
}
# tile 397 (crude arrow / orcish arrow)
{
}
# tile 398 (silver arrow)
{
}
# tile 399 (bamboo arrow / ya)
{
}
# tile 400 (crossbow bolt)
{
}
# tile 401 (dart)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 402 (throwing star / shuriken)
{
}
# tile 403 (boomerang)
{
}
# tile 404 (spear)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 405 (runed spear / elven spear)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 406 (crude spear / orcish spear)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 407 (stout spear / dwarvish spear)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 408 (silver spear)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 409 (throwing spear / javelin)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 410 (trident)
{
  model = x_spear.md2
  skin  = x_spear.png
}
# tile 411 (dagger)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 412 (runed dagger / elven dagger)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 413 (crude dagger / orcish dagger)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 414 (silver dagger)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 415 (athame)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 416 (scalpel)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 417 (knife)
{
  model = x_incisor.md2
  skin  = x_incisor.png
}
# tile 418 (stiletto)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 419 (worm tooth)
{
}
# tile 420 (crysknife)
{
  model = x_hatchet.md2
  skin  = x_hatchet.png
}
# tile 421 (axe)
{
  model = x_hatchet.md2
  skin  = x_hatchet.png
}
# tile 422 (double-headed axe / battle-axe)
{
  model = x_hatchet.md2
  skin  = x_hatchet.png
}
# tile 423 (short sword)
{
  model = x_sordwall.md2
  skin  = x_sordwall.png
  light = Sword
}
# tile 424 (runed short sword / elven short sword)
{
  model = x_sordwall.md2
  skin  = x_sordwall.png
  light = Sword
}
# tile 425 (crude short sword / orcish short sword)
{
  model = x_sordwall.md2
  skin  = x_sordwall.png
  light = Sword
}
# tile 426 (broad short sword / dwarvish short sword)
{
  model = x_sordwall.md2
  skin  = x_sordwall.png
  light = Sword
}
# tile 427 (curved sword / scimitar)
{
  model = x_sordwall.md2
  skin  = x_sordwall.png
  light = Sword
}
# tile 428 (silver saber)
{
  model = x_sordwall.md2
  skin  = x_sordwall.png
}
# tile 429 (broadsword)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 430 (runed broadsword / elven broadsword)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 431 (long sword)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 432 (two-handed sword)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 433 (samurai sword / katana)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 434 (long samurai sword / tsurugi)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 435 (runed broadsword / runesword)
{
  model = x_dsword.md2
  skin  = x_dsword.png
  light = Sword
}
# tile 436 (vulgar polearm / partisan)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 437 (hilted polearm / ranseur)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 438 (forked polearm / spetum)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 439 (single-edged polearm / glaive)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 440 (lance)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 441 (angled poleaxe / halberd)
{
  model = x_hatchet.md2
  skin  = x_hatchet.png
}
# tile 442 (long poleaxe / bardiche)
{
  model = x_hatchet.md2
  skin  = x_hatchet.png
}
# tile 443 (pole cleaver / voulge)
{
  model = x_hatchet.md2
  skin  = x_hatchet.png
}
# tile 444 (broad pick / dwarvish mattock)
{
  model = x_pick.md2
  skin  = x_pick.png
}
# tile 445 (pole sickle / fauchard)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 446 (pruning hook / guisarme)
{
}
# tile 447 (hooked polearm / bill-guisarme)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 448 (pronged polearm / lucern hammer)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 449 (beaked polearm / bec de corbin)
{
  model = x_stiletto.md2
  skin  = x_stiletto.png
}
# tile 450 (mace)
{
  model = x_mace.md2
  skin  = x_mace.png
}
# tile 451 (morning star)
{
  model = x_mace.md2
  skin  = x_mace.png
}
# tile 452 (war hammer)
{
  model = x_mallet.md2
  skin  = x_mallet.png
}
# tile 453 (club)
{
  model = x_mallet.md2
  skin  = x_mallet.png
}
# tile 454 (rubber hose)
{
}
# tile 455 (staff / quarterstaff)
{
}
# tile 456 (thonged club / aklys)
{
}
# tile 457 (flail)
{
}
# tile 458 (bullwhip)
{
}
# tile 459 (bow)
{
  model = x_lbow.md2
  skin  = x_lbow.png
}
# tile 460 (runed bow / elven bow)
{
  model = x_lbow.md2
  skin  = x_lbow.png
}
# tile 461 (crude bow / orcish bow)
{
  model = x_lbow.md2
  skin  = x_lbow.png
}
# tile 462 (long bow / yumi)
{
  model = x_lbow.md2
  skin  = x_lbow.png
}
# tile 463 (sling)
{
  model = x_hanxbow.md2
  skin  = x_hanxbow.png
}
# tile 464 (crossbow)
{
  model = x_hanxbow.md2
  skin  = x_hanxbow.png
}
# tile 465 (leather hat / elven leather helm)
{
}
# tile 466 (iron skull cap / orcish helm)
{
}
# tile 467 (hard hat / dwarvish iron helm)
{
}
# tile 468 (fedora)
{
}
# tile 469 (conical hat / cornuthaum)
{
}
# tile 470 (conical hat / dunce cap)
{
}
# tile 471 (dented pot)
{
}
# tile 472 (plumed helmet / helmet)
{
}
# tile 473 (etched helmet / helm of brilliance)
{
}
# tile 474 (crested helmet / helm of opposite alignment)
{
}
# tile 475 (visored helmet / helm of telepathy)
{
}
# tile 476 (gray dragon scale mail)
{
}
# tile 477 (silver dragon scale mail)
{
}
# tile 478 (shimmering dragon scale mail)
{
}
# tile 479 (red dragon scale mail)
{
}
# tile 480 (white dragon scale mail)
{
}
# tile 481 (orange dragon scale mail)
{
}
# tile 482 (black dragon scale mail)
{
}
# tile 483 (blue dragon scale mail)
{
}
# tile 484 (green dragon scale mail)
{
}
# tile 485 (yellow dragon scale mail)
{
}
# tile 486 (gray dragon scales)
{
}
# tile 487 (silver dragon scales)
{
}
# tile 488 (shimmering dragon scales)
{
}
# tile 489 (red dragon scales)
{
}
# tile 490 (white dragon scales)
{
}
# tile 491 (orange dragon scales)
{
}
# tile 492 (black dragon scales)
{
}
# tile 493 (blue dragon scales)
{
}
# tile 494 (green dragon scales)
{
}
# tile 495 (yellow dragon scales)
{
}
# tile 496 (plate mail)
{
}
# tile 497 (crystal plate mail)
{
}
# tile 498 (bronze plate mail)
{
}
# tile 499 (splint mail)
{
}
# tile 500 (banded mail)
{
}
# tile 501 (dwarvish mithril-coat)
{
}
# tile 502 (elven mithril-coat)
{
}
# tile 503 (chain mail)
{
}
# tile 504 (crude chain mail / orcish chain mail)
{
}
# tile 505 (scale mail)
{
}
# tile 506 (studded leather armor)
{
}
# tile 507 (ring mail)
{
}
# tile 508 (crude ring mail / orcish ring mail)
{
}
# tile 509 (leather armor)
{
}
# tile 510 (leather jacket)
{
}
# tile 511 (Hawaiian shirt)
{
}
# tile 512 (T-shirt)
{
}
# tile 513 (mummy wrapping)
{
}
# tile 514 (faded pall / elven cloak)
{
}
# tile 515 (coarse mantelet / orcish cloak)
{
}
# tile 516 (hooded cloak / dwarvish cloak)
{
}
# tile 517 (slippery cloak / oilskin cloak)
{
}
# tile 518 (robe)
{
}
# tile 519 (apron / alchemy smock)
{
}
# tile 520 (leather cloak)
{
}
# tile 521 (tattered cape / cloak of protection)
{
}
# tile 522 (opera cloak / cloak of invisibility)
{
}
# tile 523 (ornamental cope / cloak of magic resistance)
{
}
# tile 524 (piece of cloth / cloak of displacement)
{
}
# tile 525 (small shield)
{
  model = x_tshield.md2
  skin  = x_tshield.png
}
# tile 526 (blue and green shield / elven shield)
{
  model = x_tshield.md2
  skin  = x_tshield.png
}
# tile 527 (white-handed shield / Uruk-hai shield)
{
  model = x_tshield.md2
  skin  = x_tshield.png
}
# tile 528 (red-eyed shield / orcish shield)
{
  model = x_kshield.md2
  skin  = x_kshield.png
}
# tile 529 (large shield)
{
  model = x_gshield.md2
  skin  = x_gshield.png
}
# tile 530 (large round shield / dwarvish roundshield)
{
  model = x_kshield.md2
  skin  = x_kshield.png
}
# tile 531 (polished silver shield / shield of reflection)
{
  model = x_hshield.md2
  skin  = x_hshield.png
}
# tile 532 (old gloves / leather gloves)
{
}
# tile 533 (padded gloves / gauntlets of fumbling)
{
}
# tile 534 (riding gloves / gauntlets of power)
{
}
# tile 535 (fencing gloves / gauntlets of dexterity)
{
}
# tile 536 (walking shoes / low boots)
{
}
# tile 537 (hard shoes / iron shoes)
{
}
# tile 538 (jackboots / high boots)
{
}
# tile 539 (combat boots / speed boots)
{
}
# tile 540 (jungle boots / water walking boots)
{
}
# tile 541 (hiking boots / jumping boots)
{
}
# tile 542 (mud boots / elven boots)
{
}
# tile 543 (buckled boots / kicking boots)
{
}
# tile 544 (riding boots / fumble boots)
{
}
# tile 545 (snow boots / levitation boots)
{
}
# tile 546 (wooden / adornment)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 547 (granite / gain strength)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 548 (opal / gain constitution)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 549 (clay / increase accuracy)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 550 (coral / increase damage)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 551 (black onyx / protection)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 552 (moonstone / regeneration)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 553 (tiger eye / searching)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 554 (jade / stealth)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 555 (bronze / sustain ability)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 556 (agate / levitation)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 557 (topaz / hunger)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 558 (sapphire / aggravate monster)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 559 (ruby / conflict)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 560 (diamond / warning)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 561 (pearl / poison resistance)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 562 (iron / fire resistance)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 563 (brass / cold resistance)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 564 (copper / shock resistance)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 565 (twisted / free action)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 566 (steel / slow digestion)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 567 (silver / teleportation)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 568 (gold / teleport control)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 569 (ivory / polymorph)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 570 (emerald / polymorph control)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 571 (wire / invisibility)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 572 (engagement / see invisible)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 573 (shiny / protection from shape changers)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 574 (circular / amulet of ESP)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 575 (spherical / amulet of life saving)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 576 (oval / amulet of strangulation)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 577 (triangular / amulet of restful sleep)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 578 (pyramidal / amulet versus poison)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 579 (square / amulet of change)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 580 (concave / amulet of unchanging)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 581 (hexagonal / amulet of reflection)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 582 (octagonal / amulet of magical breathing)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 583 (Amulet of Yendor / cheap plastic imitation of the Amulet of Yendor)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 584 (Amulet of Yendor)
{
  model = x_sbrace.md2
  skin  = x_sbrace.png
}
# tile 585 (large box)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 586 (chest)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 587 (ice box)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 588 (bag / sack)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 589 (bag / oilskin sack)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 590 (bag / bag of holding)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 591 (bag / bag of tricks)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 592 (key / skeleton key)
{
  model = x_pick.md2
  skin  = x_pick.png
}
# tile 593 (lock pick)
{
  model = x_pick.md2
  skin  = x_pick.png
}
# tile 594 (credit card)
{
  model = x_pick.md2
  skin  = x_pick.png
}
# tile 595 (candle / tallow candle)
{
  model = x_torch.md2
  skin  = x_torch.png
  light = Candle
}
# tile 596 (candle / wax candle)
{
  model = x_torch.md2
  skin  = x_torch.png
  light = Candle
}
# tile 597 (brass lantern)
{
  model = x_torch.md2
  skin  = x_torch.png
  light = BrassLantern
}
# tile 598 (lamp / oil lamp)
{
  model = x_torch.md2
  skin  = x_torch.png
  light = Lamp
}
# tile 599 (lamp / magic lamp)
{
  model = x_torch.md2
  skin  = x_torch.png
  light = Lamp
}
# tile 600 (expensive camera)
{
  model = x_torch.md2
  skin  = x_torch.png
}
# tile 601 (looking glass / mirror)
{
}
# tile 602 (glass orb / crystal ball)
{
}
# tile 603 (lenses)
{
}
# tile 604 (blindfold)
{
}
# tile 605 (towel)
{
}
# tile 606 (saddle)
{
}
# tile 607 (leash)
{
}
# tile 608 (stethoscope)
{
}
# tile 609 (tinning kit)
{
  model = x_achest.md2
  skin  = x_achest.png
}
# tile 610 (tin opener)
{
  model = x_pick.md2
  skin  = x_pick.png
}
# tile 611 (can of grease)
{
  light = OilPotion
}
# tile 612 (figurine)
{
}
# tile 613 (magic marker)
{
}
# tile 614 (land mine object)
{
}
# tile 615 (bear trap object)
{
}
# tile 616 (whistle / tin whistle)
{
}
# tile 617 (whistle / magic whistle)
{
}
# tile 618 (flute / wooden flute)
{
}
# tile 619 (flute / magic flute)
{
}
# tile 620 (horn / tooled horn)
{
}
# tile 621 (horn / frost horn)
{
}
# tile 622 (horn / fire horn)
{
}
# tile 623 (horn / horn of plenty)
{
}
# tile 624 (harp / wooden harp)
{
}
# tile 625 (harp / magic harp)
{
}
# tile 626 (bell)
{
}
# tile 627 (bugle)
{
}
# tile 628 (drum / leather drum)
{
}
# tile 629 (drum / drum of earthquake)
{
}
# tile 630 (pick-axe)
{
  model = x_pick.md2
  skin  = x_pick.png
}
# tile 631 (iron hook / grappling hook)
{
}
# tile 632 (unicorn horn)
{
}
# tile 633 (candelabrum / Candelabrum of Invocation)
{
  light = Candelabrum
}
# tile 634 (silver bell / Bell of Opening)
{
}
# tile 635 (tripe ration)
{
}
# tile 636 (corpse)
{
}
# tile 637 (egg)
{
}
# tile 638 (meatball)
{
}
# tile 639 (meat stick)
{
}
# tile 640 (huge chunk of meat)
{
}
# tile 641 (meat ring)
{
}
# tile 642 (kelp frond)
{
}
# tile 643 (eucalyptus leaf)
{
}
# tile 644 (apple)
{
}
# tile 645 (orange)
{
}
# tile 646 (pear)
{
}
# tile 647 (melon)
{
}
# tile 648 (banana)
{
}
# tile 649 (carrot)
{
}
# tile 650 (sprig of wolfsbane)
{
}
# tile 651 (clove of garlic)
{
}
# tile 652 (slime mold)
{
}
# tile 653 (lump of royal jelly)
{
}
# tile 654 (cream pie)
{
}
# tile 655 (candy bar)
{
}
# tile 656 (fortune cookie)
{
}
# tile 657 (pancake)
{
}
# tile 658 (lembas wafer)
{
}
# tile 659 (cram ration)
{
}
# tile 660 (food ration)
{
}
# tile 661 (K-ration)
{
}
# tile 662 (C-ration)
{
}
# tile 663 (tin)
{
}
# tile 664 (ruby / gain ability)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 665 (pink / restore ability)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 666 (orange / confusion)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 667 (yellow / blindness)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 668 (emerald / paralysis)
{
  model = x_potion.md2
  skin  = x_gpotion.png
  light = OilPotion
  scale = 3;
}
# tile 669 (dark green / speed)
{
  model = x_potion.md2
  skin  = x_gpotion.png
  light = OilPotion
  scale = 3;
}
# tile 670 (cyan / levitation)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 671 (sky blue / hallucination)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 672 (brilliant blue / invisibility)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 673 (magenta / see invisible)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 674 (purple-red / healing)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 675 (puce / extra healing)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 676 (milky / gain level)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 677 (swirly / enlightenment)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 678 (bubbly / monster detection)
{
  model = x_potion.md2
  skin  = x_gpotion.png
  light = OilPotion
  scale = 3;
}
# tile 679 (smoky / object detection)
{
  model = x_potion.md2
  skin  = x_gpotion.png
  light = OilPotion
  scale = 3;
}
# tile 680 (cloudy / gain energy)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 681 (effervescent / sleeping)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 682 (black / full healing)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 683 (golden / polymorph)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 684 (brown / booze)
{
  model = x_potion.md2
  skin  = x_rpotion.png
  light = OilPotion
  scale = 3;
}
# tile 685 (fizzy / sickness)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 686 (dark / fruit juice)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 687 (white / acid)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 688 (murky / oil)
{
  model = x_potion.md2
  skin  = x_ypotion.png
  light = OilPotion
  scale = 3;
}
# tile 689 (clear / water)
{
  model = x_potion.md2
  skin  = x_bpotion.png
  light = OilPotion
  scale = 3;
}
# tile 690 (ZELGO MER / enchant armor)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 691 (JUYED AWK YACC / destroy armor)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 692 (NR 9 / confuse monster)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 693 (XIXAXA XOXAXA XUXAXA / scare monster)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 694 (PRATYAVAYAH / remove curse)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 695 (DAIYEN FOOELS / enchant weapon)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 696 (LEP GEX VEN ZEA / create monster)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 697 (PRIRUTSENIE / taming)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 698 (ELBIB YLOH / genocide)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 699 (VERR YED HORRE / light)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 700 (VENZAR BORGAVVE / teleportation)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 701 (THARR / gold detection)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 702 (YUM YUM / food detection)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 703 (KERNOD WEL / identify)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 704 (ELAM EBOW / magic mapping)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 705 (DUAM XNAHT / amnesia)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 706 (ANDOVA BEGARIN / fire)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 707 (KIRJE / earth)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 708 (VE FORBRYDERNE / punishment)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 709 (HACKEM MUCHE / charging)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 710 (VELOX NEB / stinking cloud)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 711 (FOOBIE BLETCH)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 712 (TEMOV)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 713 (GARVEN DEH)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 714 (READ ME)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 715 (stamped / mail)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 716 (unlabeled / blank paper)
{
  model = x_identify.md2
  skin  = x_identify.png
  scale = 3;
}
# tile 717 (parchment / dig)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 718 (vellum / magic missile)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 719 (ragged / fireball)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 720 (dog eared / cone of cold)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 721 (mottled / sleep)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 722 (stained / finger of death)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 723 (cloth / light)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 724 (leather / detect monsters)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 725 (white / healing)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 726 (pink / knock)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 727 (red / force bolt)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 728 (orange / confuse monster)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 729 (yellow / cure blindness)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 730 (velvet / drain life)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 731 (light green / slow monster)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 732 (dark green / wizard lock)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 733 (turquoise / create monster)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 734 (cyan / detect food)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 735 (light blue / cause fear)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 736 (dark blue / clairvoyance)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 737 (indigo / cure sickness)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 738 (magenta / charm monster)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 739 (purple / haste self)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 740 (violet / detect unseen)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 741 (tan / levitation)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 742 (plaid / extra healing)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 743 (light brown / restore ability)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 744 (dark brown / invisibility)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 745 (gray / detect treasure)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 746 (wrinkled / remove curse)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 747 (dusty / magic mapping)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 748 (bronze / identify)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 749 (copper / turn undead)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 750 (silvery / polymorph)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 751 (gold / teleport away)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 752 (glittering / create familiar)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 753 (shining / cancellation)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 754 (dull / protection)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 755 (thin / jumping)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 756 (thick / stone to flesh)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 757 (plain / blank paper)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 758 (papyrus / Book of the Dead)
{
  model = x_book.md2
  skin  = x_book.png
}
# tile 759 (glass / light)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 760 (balsa / secret door detection)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 761 (crystal / enlightenment)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 762 (maple / create monster)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 763 (pine / wishing)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 764 (oak / nothing)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 765 (ebony / striking)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 766 (marble / make invisible)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 767 (tin / slow monster)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 768 (brass / speed monster)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 769 (copper / undead turning)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 770 (silver / polymorph)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 771 (platinum / cancellation)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 772 (iridium / teleportation)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 773 (zinc / opening)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 774 (aluminum / locking)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 775 (uranium / probing)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 776 (iron / digging)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 777 (steel / magic missile)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 778 (hexagonal / fire)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 779 (short / cold)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 780 (runed / sleep)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 781 (long / death)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 782 (curved / lightning)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 783 (forked)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 784 (spiked)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 785 (jeweled)
{
  model = x_wandm.md2
  skin  = x_wandm.png
}
# tile 786 (gold piece)
{
  model = gold.md2
  skin  = gold.png
}
# tile 787 (white / dilithium crystal)
{
  model = gem.md2
  skin  = gem_white.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 788 (white / diamond)
{
  model = gem.md2
  skin  = gem_white.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 789 (red / ruby)
{
  model = gem.md2
  skin  = gem_red.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 790 (orange / jacinth)
{
  model = gem.md2
  skin  = gem_orange.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 791 (blue / sapphire)
{
  model = gem.md2
  skin  = gem_blue.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 792 (black / black opal)
{
  model = gem.md2
  skin  = gem_black.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 793 (green / emerald)
{
  model = gem.md2
  skin  = gem_green.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 794 (green / turquoise)
{
  model = gem.md2
  skin  = gem_green.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 795 (yellow / citrine)
{
  model = gem.md2
  skin  = gem_yellow.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 796 (green / aquamarine)
{
  model = gem.md2
  skin  = gem_green.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 797 (yellowish brown / amber)
{
  model = gem.md2
  skin  = gem_yelbrn.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 798 (yellowish brown / topaz)
{
  model = gem.md2
  skin  = gem_yelbrn.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 799 (black / jet)
{
  model = gem.md2
  skin  = gem_black.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 800 (white / opal)
{
  model = gem.md2
  skin  = gem_white.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 801 (yellow / chrysoberyl)
{
  model = gem.md2
  skin  = gem_yellow.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 802 (red / garnet)
{
  model = gem.md2
  skin  = gem_red.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 803 (violet / amethyst)
{
  model = gem.md2
  skin  = gem_violet.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 804 (red / jasper)
{
  model = gem.md2
  skin  = gem_red.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 805 (violet / fluorite)
{
  model = gem.md2
  skin  = gem_violet.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 806 (black / obsidian)
{
  model = gem.md2
  skin  = gem_black.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 807 (orange / agate)
{
  model = gem.md2
  skin  = gem_orange.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 808 (green / jade)
{
  model = gem.md2
  skin  = gem_green.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 809 (white / worthless piece of white glass)
{
  model = gem.md2
  skin  = gem_white.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 810 (blue / worthless piece of blue glass)
{
  model = gem.md2
  skin  = gem_blue.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 811 (red / worthless piece of red glass)
{
  model = gem.md2
  skin  = gem_red.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 812 (yellowish brown / worthless piece of yellowish brown glass)
{
  model = gem.md2
  skin  = gem_yelbrn.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 813 (orange / worthless piece of orange glass)
{
  model = gem.md2
  skin  = gem_orange.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 814 (yellow / worthless piece of yellow glass)
{
  model = gem.md2
  skin  = gem_yellow.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 815 (black / worthless piece of black glass)
{
  model = gem.md2
  skin  = gem_black.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 816 (green / worthless piece of green glass)
{
  model = gem.md2
  skin  = gem_green.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 817 (violet / worthless piece of violet glass)
{
  model = gem.md2
  skin  = gem_violet.png
  material = Gem
  scale = 0.5
  flags = R
}
# tile 818 (gray / luckstone)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 819 (gray / loadstone)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 820 (gray / touchstone)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 821 (gray / flint)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 822 (rock)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 823 (boulder)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 824 (statue)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 825 (heavy iron ball)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 826 (iron chain)
{
  model = x_ironball.md2
  skin  = x_ironball.png
}
# tile 827 (splash of venom / blinding venom)
{
}
# tile 828 (splash of venom / acid venom)
{
}
