# tile 829 (dark part of a room)
{
}
# tile 830 (wall 0)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 831 (wall 1)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 832 (wall 2)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 833 (wall 3)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 834 (wall 4)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 835 (wall 5)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 836 (wall 6)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 837 (wall 7)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 838 (wall 8)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 839 (wall 9)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 840 (wall 10)
{
  model = wall.md2
  skin  = wall.png
  flags = F
}
# tile 841 (doorway)
{
  model = doorway.md2
  skin  = wood1.png
  flags = M
}
# tile 842 (open door)
{
  model = open_door.md2
  skin  = door.png
  rotate = 0
  flags = M
}
# tile 843 (open vertical door)
{
  model = open_door.md2
  skin  = door.png
  rotate = 90
  flags = M
}
# tile 844 (closed door)
{
  model = closed_door.md2
  skin  = door.png
  rotate = 0
}
# tile 845 (closed vertical door)
{
  model = closed_door.md2
  skin  = door.png
  rotate = 90
}
# tile 846 (iron bars)
{
}
# tile 847 (tree)
{
}
# tile 848 (floor of a room)
{
  model = floor.md2
  skin  = floor.png
}
# tile 849 (corridor)
{
  model = floor.md2
  skin  = floor.png
}
# tile 850 (lit corridor)
{
  model = floor.md2
  skin  = floor.png
}
# tile 851 (staircase up)
{
  model = staircase.md2
  skin  = staircase.png
  rotate = 90
}
# tile 852 (staircase down)
{
  model = downstair.md2
  skin  = downstair.png
  rotate = 0
  flags = F
}
# tile 853 (ladder up)
{
  model = staircase.md2
  skin  = staircase.png
  rotate = 90
}
# tile 854 (ladder down)
{
  model = downstair.md2
  skin  = downstair.png
  rotate = 0
  flags = F
}
# tile 855 (altar)
{
}
# tile 856 (grave)
{
}
# tile 857 (opulent throne)
{
}
# tile 858 (sink)
{
  model = fountain.md2
  skin  = fountain.png
}
# tile 859 (fountain)
{
  model = fountain.md2
  skin  = fountain.png
}
# tile 860 (pool of water)
{
  model = floor.md2
  skin  = water.png
  flags = FM
}
# tile 861 (ice)
{
  model = floor.md2
  skin  = ice.png
  flags = FM
}
# tile 862 (molten lava)
{
  model = floor.md2
  skin  = lava.png
  flags = FM
}
# tile 863 (lowered vertical drawbridge)
{
}
# tile 864 (lowered drawbridge)
{
}
# tile 865 (raised drawbridge)
{
}
# tile 866 (raised vertical drawbridge)
{
}
# tile 867 (air)
{
}
# tile 868 (cloud)
{
}
# tile 869 (water)
{
  model = floor.md2
  skin  = water.png
  flags = FM
}
# tile 870 (arrow trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 871 (dart trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 872 (falling rock trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 873 (squeaky board)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 874 (bear trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 875 (land mine)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 876 (rolling boulder trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 877 (sleeping gas trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 878 (rust trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 879 (fire trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 880 (pit)
{
  model = pit.md2
  skin  = pit.png
  flags = F
}
# tile 881 (spiked pit)
{
  model = pit_spiked.md2
  skin  = pit_spiked.png
  flags = F
}
# tile 882 (hole)
{
  model = pit.md2
  skin  = pit.png
}
# tile 883 (trap door)
{
  model = pit.md2
  skin  = pit.png
}
# tile 884 (teleportation trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 885 (level teleporter)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 886 (magic portal)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 887 (web)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 888 (statue trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 889 (magic trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 890 (anti-magic field)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 891 (polymorph trap)
{
  model = x_beartrap.md2
  skin  = x_beartrap.png
}
# tile 892 (wall A)
{
  model = wall.md2
  skin  = wall.png
}
# tile 893 (wall B)
{
  model = wall.md2
  skin  = wall.png
}
# tile 894 (wall C)
{
  model = wall.md2
  skin  = wall.png
}
# tile 895 (wall D)
{
  model = wall.md2
  skin  = wall.png
}
# tile 896 (cmap / dig beam)
{
}
# tile 897 (cmap / camera flash)
{
}
# tile 898 (cmap / thrown boomerang, open left)
{
}
# tile 899 (cmap / thrown boomerang, open right)
{
}
# tile 900 (cmap / magic shield 1)
{
  model = x_protect.md2
  skin  = x_protect.png
  rotate = 0
}
# tile 901 (cmap / magic shield 2)
{
  model = x_protect.md2
  skin  = x_protect.png
  rotate = -90
}
# tile 902 (cmap / magic shield 3)
{
  model = x_protect.md2
  skin  = x_protect.png
  rotate = -180
}
# tile 903 (cmap / magic shield 4)
{
  model = x_protect.md2
  skin  = x_protect.png
  rotate = -270
}
# tile 904 (cmap / swallow top left)
{
}
# tile 905 (cmap / swallow top center)
{
}
# tile 906 (cmap / swallow top right)
{
}
# tile 907 (cmap / swallow middle left)
{
}
# tile 908 (cmap / swallow middle right)
{
}
# tile 909 (cmap / swallow bottom left)
{
}
# tile 910 (cmap / swallow bottom center)
{
}
# tile 911 (cmap / swallow bottom right)
{
}
# tile 957 (explosion dark 0)
{
}
# tile 958 (explosion dark 1)
{
}
# tile 959 (explosion dark 2)
{
}
# tile 960 (explosion dark 3)
{
}
# tile 961 (explosion dark 4)
{
}
# tile 962 (explosion dark 5)
{
}
# tile 963 (explosion dark 6)
{
}
# tile 964 (explosion dark 7)
{
}
# tile 965 (explosion dark 8)
{
}
# tile 957 (explosion noxious 0)
{
}
# tile 958 (explosion noxious 1)
{
}
# tile 959 (explosion noxious 2)
{
}
# tile 960 (explosion noxious 3)
{
}
# tile 961 (explosion noxious 4)
{
}
# tile 962 (explosion noxious 5)
{
}
# tile 963 (explosion noxious 6)
{
}
# tile 964 (explosion noxious 7)
{
}
# tile 965 (explosion noxious 8)
{
}
# tile 957 (explosion muddy 0)
{
}
# tile 958 (explosion muddy 1)
{
}
# tile 959 (explosion muddy 2)
{
}
# tile 960 (explosion muddy 3)
{
}
# tile 961 (explosion muddy 4)
{
}
# tile 962 (explosion muddy 5)
{
}
# tile 963 (explosion muddy 6)
{
}
# tile 964 (explosion muddy 7)
{
}
# tile 965 (explosion muddy 8)
{
}
# tile 957 (explosion wet 0)
{
}
# tile 958 (explosion wet 1)
{
}
# tile 959 (explosion wet 2)
{
}
# tile 960 (explosion wet 3)
{
}
# tile 961 (explosion wet 4)
{
}
# tile 962 (explosion wet 5)
{
}
# tile 963 (explosion wet 6)
{
}
# tile 964 (explosion wet 7)
{
}
# tile 965 (explosion wet 8)
{
}
# tile 957 (explosion magical 0)
{
}
# tile 958 (explosion magical 1)
{
}
# tile 959 (explosion magical 2)
{
}
# tile 960 (explosion magical 3)
{
}
# tile 961 (explosion magical 4)
{
}
# tile 962 (explosion magical 5)
{
}
# tile 963 (explosion magical 6)
{
}
# tile 964 (explosion magical 7)
{
}
# tile 965 (explosion magical 8)
{
}
# tile 957 (explosion fiery 0)
{
}
# tile 958 (explosion fiery 1)
{
}
# tile 959 (explosion fiery 2)
{
}
# tile 960 (explosion fiery 3)
{
}
# tile 961 (explosion fiery 4)
{
}
# tile 962 (explosion fiery 5)
{
}
# tile 963 (explosion fiery 6)
{
}
# tile 964 (explosion fiery 7)
{
}
# tile 965 (explosion fiery 8)
{
}
# tile 957 (explosion frosty 0)
{
}
# tile 958 (explosion frosty 1)
{
}
# tile 959 (explosion frosty 2)
{
}
# tile 960 (explosion frosty 3)
{
}
# tile 961 (explosion frosty 4)
{
}
# tile 962 (explosion frosty 5)
{
}
# tile 963 (explosion frosty 6)
{
}
# tile 964 (explosion frosty 7)
{
}
# tile 965 (explosion frosty 8)
{
}
# tile 975 (zap 0 0)
{
  model = zap.md2
  skin  = zap_magic.png
  rotate = 90
}
# tile 976 (zap 0 1)
{
  model = zap.md2
  skin  = zap_magic.png
  rotate = 0
}
# tile 977 (zap 0 2)
{
  model = zap_diag.md2
  skin  = zap_magic.png
  rotate = -45
}
# tile 978 (zap 0 3)
{
  model = zap_diag.md2
  skin  = zap_magic.png
  rotate = 45
}
# tile 979 (zap 1 0)
{
  model = zap.md2
  skin  = zap_fire.png
  rotate = 90
}
# tile 980 (zap 1 1)
{
  model = zap.md2
  skin  = zap_fire.png
  rotate = 0
}
# tile 981 (zap 1 2)
{
  model = zap_diag.md2
  skin  = zap_fire.png
  rotate = -45
}
# tile 982 (zap 1 3)
{
  model = zap_diag.md2
  skin  = zap_fire.png
  rotate = 45
}
# tile 983 (zap 2 0)
{
  model = zap.md2
  skin  = zap_cold.png
  rotate = 90
}
# tile 984 (zap 2 1)
{
  model = zap.md2
  skin  = zap_cold.png
  rotate = 0
}
# tile 985 (zap 2 2)
{
  model = zap_diag.md2
  skin  = zap_cold.png
  rotate = -45
}
# tile 986 (zap 2 3)
{
  model = zap_diag.md2
  skin  = zap_cold.png
  rotate = 45
}
# tile 987 (zap 3 0)
{
  model = zap.md2
  skin  = zap_sleep.png
  rotate = 90
}
# tile 988 (zap 3 1)
{
  model = zap.md2
  skin  = zap_sleep.png
  rotate = 0
}
# tile 989 (zap 3 2)
{
  model = zap_diag.md2
  skin  = zap_sleep.png
  rotate = -45
}
# tile 990 (zap 3 3)
{
  model = zap_diag.md2
  skin  = zap_sleep.png
  rotate = 45
}
# tile 991 (zap 4 0)
{
  model = zap.md2
  skin  = zap_death.png
  rotate = 90
}
# tile 992 (zap 4 1)
{
  model = zap.md2
  skin  = zap_death.png
  rotate = 0
}
# tile 993 (zap 4 2)
{
  model = zap_diag.md2
  skin  = zap_death.png
  rotate = -45
}
# tile 994 (zap 4 3)
{
  model = zap_diag.md2
  skin  = zap_death.png
  rotate = 45
}
# tile 995 (zap 5 0)
{
  model = zap.md2
  skin  = zap_lightning.png
  rotate = 90
}
# tile 996 (zap 5 1)
{
  model = zap.md2
  skin  = zap_lightning.png
  rotate = 0
}
# tile 997 (zap 5 2)
{
  model = zap_diag.md2
  skin  = zap_lightning.png
  rotate = -45
}
# tile 998 (zap 5 3)
{
  model = zap_diag.md2
  skin  = zap_lightning.png
  rotate = 45
}
# tile 999 (zap 6 0)
{
  model = zap.md2
  skin  = zap_gaseous.png
  rotate = 90
}
# tile 1000 (zap 6 1)
{
  model = zap.md2
  skin  = zap_gaseous.png
  rotate = 0
}
# tile 1001 (zap 6 2)
{
  model = zap_diag.md2
  skin  = zap_gaseous.png
  rotate = -45
}
# tile 1002 (zap 6 3)
{
  model = zap_diag.md2
  skin  = zap_gaseous.png
  rotate = 45
}
# tile 1003 (zap 7 0)
{
  model = zap.md2
  skin  = zap_acidic.png
  rotate = 90
}
# tile 1004 (zap 7 1)
{
  model = zap.md2
  skin  = zap_acidic.png
  rotate = 0
}
# tile 1005 (zap 7 2)
{
  model = zap_diag.md2
  skin  = zap_acidic.png
  rotate = -45
}
# tile 1006 (zap 7 3)
{
  model = zap_diag.md2
  skin  = zap_acidic.png
  rotate = 45
}
# tile 1007 (warning 0)
{
}
# tile 1008 (warning 1)
{
}
# tile 1009 (warning 2)
{
}
# tile 1010 (warning 3)
{
}
# tile 1011 (warning 4)
{
}
# tile 1012 (warning 5)
{
}
# tile 1013 (sub mine walls 0)
{
  model = mine_A.md2
  skin  = mine.png
  rotate = 0
  flags = F
}
# tile 1014 (sub mine walls 1)
{
  model = mine_A.md2
  skin  = mine.png
  rotate = -90
  flags = F
}
# tile 1015 (sub mine walls 2)
{
  model = mine_B.md2
  skin  = mine.png
  rotate = 0
  flags = F
}
# tile 1016 (sub mine walls 3)
{
  model = mine_B.md2
  skin  = mine.png
  rotate = -90
  flags = F
}
# tile 1017 (sub mine walls 4)
{
  model = mine_B.md2
  skin  = mine.png
  rotate = 90
  flags = F
}
# tile 1018 (sub mine walls 5)
{
  model = mine_B.md2
  skin  = mine.png
  rotate = 180
  flags = F
}
# tile 1019 (sub mine walls 6)
{
  model = mine_D.md2
  skin  = mine.png
  rotate = 0
  flags = F
}
# tile 1020 (sub mine walls 7)
{
  model = mine_C.md2
  skin  = mine.png
  rotate = 90
  flags = F
}
# tile 1021 (sub mine walls 8)
{
  model = mine_C.md2
  skin  = mine.png
  rotate = -90
  flags = F
}
# tile 1022 (sub mine walls 9)
{
  model = mine_C.md2
  skin  = mine.png
  rotate = 180
  flags = F
}
# tile 1023 (sub mine walls 10)
{
  model = mine_C.md2
  skin  = mine.png
  rotate = 0
  flags = F
}
# tile 1024 (sub gehennom walls 0)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1025 (sub gehennom walls 1)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1026 (sub gehennom walls 2)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1027 (sub gehennom walls 3)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1028 (sub gehennom walls 4)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1029 (sub gehennom walls 5)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1030 (sub gehennom walls 6)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1031 (sub gehennom walls 7)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1032 (sub gehennom walls 8)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1033 (sub gehennom walls 9)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1034 (sub gehennom walls 10)
{
  model = wall.md2
  skin  = wall_hell.png
  flags = F
}
# tile 1024 (sub knox walls 0)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1025 (sub knox walls 1)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1026 (sub knox walls 2)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1027 (sub knox walls 3)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1028 (sub knox walls 4)
{
  model = wall.md2
  skin  = wall_knox.png
}
# tile 1029 (sub knox walls 5)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1030 (sub knox walls 6)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1031 (sub knox walls 7)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1032 (sub knox walls 8)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1033 (sub knox walls 9)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1034 (sub knox walls 10)
{
  model = wall.md2
  skin  = wall_knox.png
  flags = F
}
# tile 1046 (sub sokoban walls 0)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1047 (sub sokoban walls 1)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1048 (sub sokoban walls 2)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1049 (sub sokoban walls 3)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1050 (sub sokoban walls 4)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1051 (sub sokoban walls 5)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1052 (sub sokoban walls 6)
{
  model = wall.md2
  skin  = wall_sokoban.png
}
# tile 1053 (sub sokoban walls 7)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1054 (sub sokoban walls 8)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1055 (sub sokoban walls 9)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1056 (sub sokoban walls 10)
{
  model = wall.md2
  skin  = wall_sokoban.png
  flags = F
}
# tile 1057 (sub mine floor)
{
  model = floor.md2
  skin  = mine_floor.png
}
# tile 1058 (sub sokoban floor)
{
  model = floor.md2
  skin  = sokoban_floor.png
}
# tile 1059 (sub knox floor)
{
  model = floor.md2
  skin  = sokoban_floor.png
}
# tile 1060 (sub gehennom floor)
{
  model = floor.md2
  skin  = hell_floor.png
}
# tile 1061 (sub quest floor)
{
  model = floor.md2
  skin  = quest_floor.png
}
# tile 1062 (sub astral floor)
{
  model = floor.md2
  skin  = astral_floor.png
}
# tile 1063 (sub cave floor)
{
  model = floor.md2
  skin  = cave_floor.png
}
# tile 1064 (sub beach floor)
{
  model = floor.md2
  skin  = beach_floor.png
}
